name: kondebili_collect
description: "Application de collecte de données"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  awesome_dialog: ^3.2.1
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  dropdown_search: ^5.0.6
  date_field: ^5.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/


flutter_native_splash:
  color: "#eaf0ee"
  color_dark: "#272727"
  image: assets/logos/splash_screen_logo.png
  image_dark: assets/logos/splash_screen_logo.png

  android_12:
    image: assets/logos/splash_screen_logo.png
    icon_background_color: "#eaf0ee"
    image_dark: assets/logos/splash_screen_logo.png
    icon_background_color_dark: "#272727"
